Add MCDReforged-Remote Plugin
MCDReforged/PluginCatalogue pull request #108
Opened 2021-05-30 17:09 UTC by Cubik65536

> 一个MCDR插件+Java库，允许用户通过该库实现QQ，MC双向聊天，服务器控制等功能

会进行长期维护，添加并优化各种功能

2021-05-30 23:27 UTC, zhang-anzhi requested changes

2021-05-30 23:27 UTC, zhang-anzhi commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
插件分类错误

2021-05-30 23:27 UTC, zhang-anzhi commented on readme_cn.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | 一个MCDR插件+Java库，允许用户通过该库实现QQ，MC双向聊天，服务器控制等功能 |
同上

2021-05-30 23:46 UTC, Cubik65536 commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
> 插件分类错误

我需要对此提出以下疑问：
- 我应该算成什么类型？
- 服务器管理类具体要求？我的插件并非只有通过QQ控制一项功能，该插件主要目的就是远程**控制服务器**

2021-05-31 01:28 UTC, zhang-anzhi commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
根据你的插件介绍，目的如下
- 主要目的：`一个MCDR插件+Java库`，这属于API
- 次要目的：`允许用户通过该库实现QQ，MC双向聊天`，这属于玩家交流
- 附加目的：`服务器控制`，这属于服务器控制

2021-05-31 01:29 UTC, zhang-anzhi commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
并且由于你的服务器控制是远程控制，所以该功能可以算水桶革命

2021-05-31 01:33 UTC, Cubik65536 commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
> 根据你的插件介绍，目的如下
> 
> * 主要目的：`一个MCDR插件+Java库`，这属于API
> * 次要目的：`允许用户通过该库实现QQ，MC双向聊天`，这属于玩家交流
> * 附加目的：`服务器控制`，这属于服务器控制

- `一个MCDR插件+Java库` 只是一个附加介绍，解释插件程序的组成部分。
- 我认为为其他MCDR插件提供接口才叫API，但我这个插件并不会为任何其他MCDR插件提供任何接口。此外，我开发本插件的**主要目的**就是服务器控制。所以我在提交时填写了服务器控制类型。
- 我仍不清楚`水桶革命`的具体定位

2021-05-31 01:42 UTC, zhang-anzhi commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
不管你认为你是什么类型，你的介绍写的是一个库

2021-05-31 01:52 UTC, Cubik65536 commented on readme.md
> +| [MCDReforged-Remote](https://github.com/CuBitStudio/MCDReforged-Remote) | [Cubik65536](https://github.com/Cubik65536) | A MCDR plugin and a Java library, connecting QQ and Minecraft & allowing user
> 不管你认为你是什么类型，你的介绍写的是一个库

已移动至API类型

2021-05-31 01:58 UTC, merged