Add plugin Renewability
MCDReforged/PluginCatalogue pull request #123
Opened 2021-08-09 08:18 UTC by Fidelxyz

A plugin that allows players to clone non-renewable items.

2021-08-09 11:10 UTC, zhang-anzhi requested changes
中英不一致

2021-08-09 11:10 UTC, zhang-anzhi commented on readme.md
> +| [Renewability](https://github.com/Fidelxyz/MCDR-Renewability/) | [XuanYun_Fidel](https://github.com/Fidelxyz) | Allows players to clone non-renewable items | :large_blue_circle: |
中英不一致

2021-08-09 11:10 UTC, zhang-anzhi commented on readme_cn.md
> +| [Renewability](https://github.com/Fidelxyz/MCDR-Renewability/) | [XuanYun_Fidel](https://github.com/Fidelxyz) | 允许玩家复制不可再生物品 | :large_blue_circle: |
中英不一致

2021-08-09 11:37 UTC, ra1ny-yuki commented
之前还合并了一个#124，麻烦先同步一下再作修改

2021-08-09 11:56 UTC, zhang-anzhi commented
有修改，你先自己合并一下吧

2021-08-10 15:19 UTC, Fidelxyz commented
@zhang-anzhi 请问下是哪里不一致呢 clone & copy?

2021-08-11 00:21 UTC, ra1ny-yuki commented
当时我看的时候有两个pr，那个我检查没啥问题就先合并了，然后这个因为是对同一个文件的修改就冲突了，得麻烦你从这里fetch upstream一下然后在此基础上添加你自己的插件内容

2021-08-11 02:32 UTC, merged