Add Plugin HiToKoTo
MCDReforged/PluginCatalogue pull request #218
Opened 2022-07-21 14:24 UTC by MRNOBODY-ZST

2022-07-21 14:44 UTC, AnzhiZhang commented
Tag is wrong, it should be `information`.

2022-07-21 14:45 UTC, AnzhiZhang requested changes

2022-07-21 14:45 UTC, AnzhiZhang commented on plugins/hitokoto/plugin_info.json
> +    "labels": ["tool"],
Label is wrong, it should be information.

2022-07-22 14:48 UTC, AnzhiZhang approved these changes

2022-07-22 14:49 UTC, alex3236 requested changes
- Move English description to English README or just remove it.
- Add a requirements.txt in your repo to show your requirement`requests`

2022-07-25 10:36 UTC, AnzhiZhang requested changes
If you do not need introduction, please remove README.md

2022-07-28 09:40 UTC, closed without merging