mirror control: change readme file
MCDReforged/PluginCatalogue pull request #229
Opened 2022-12-07 09:36 UTC by charassss

使可以直接跳转到[English version]而不会404

2022-12-07 10:22 UTC, AnzhiZhang requested changes

2022-12-07 10:22 UTC, AnzhiZhang commented on plugins/mirror_control/plugin_info.json
> +    "en_us": "readme.md",
与仓库内文件名称不对应

2022-12-07 10:25 UTC, charassss commented on plugins/mirror_control/plugin_info.json
> +    "en_us": "readme.md",
本地为readme.md, 原因是因为windows大小写不敏感导致没有提交这个文件.已手动在github仓库中修改

2022-12-07 11:01 UTC, merged

2023-02-21 16:18 UTC, Fallen-Breath commented
readme-zh_cn.md 文件名错误