add baidu_netdisk_backup plugin
MCDReforged/PluginCatalogue pull request #347
Opened 2024-05-30 05:13 UTC by moran0710

---

## 检查以下事项 | Check the following:

- 仓库 URL、分支和 `related_path` 正确且 `mcdreforged.plugin.json` 位于应当存在的位置
  Repository URL, branch and `related_path` are correct and `mcdreforged.plugin.json` file exists at the correct path

- 根据 [文档](https://mcdreforged.readthedocs.io/zh_CN/latest/plugin_dev/plugin_catalogue.html#label)，检查插件标签正确且合适  
  Plugin labels are correct and appropriate according to [documentation](https://mcdreforged.readthedocs.io/en/latest/plugin_dev/plugin_catalogue.html#label)

- 确保 `mcdreforged.plugin.json` 和 `plugin_info.json` 中的插件 ID 与在本仓库创建的文件夹名称一致
  Plugin ID in `mcdreforged.plugin.json` and `plugin_info.json` match the name of the folder created in this repository

- 在介绍中简要阐明插件功能，在 README 中详细阐明插件用法，避免含糊不清。确保潜在用户有理由考虑使用您的插件
  Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the README. Avoid vague descriptions. Ensure that potential users have a reason to consider using your plugin

- [x] 我已检查并确认以上所有项目
  I have checked and confirmed all the above

2024-05-30 12:56 UTC, Ra1ny-Yuki commented
暂无法予以合并，插件元数据有个json语法错误。此外，建议在插件源码目录下新增requirements.txt写明第三方库依赖以使插件库可在插件库中正确展示依赖（不写可能会导致使用插件管理器安装该插件时出现依赖缺失）

2024-05-30 13:03 UTC, moran0710 commented
已经在我的插件仓库修复了元数据的语法错误（上学上昏头把json当字典写了，也脑子一抽没去看检查，抱歉
requirements.txt 已经加入

2024-05-30 13:16 UTC, AnzhiZhang commented on plugins/baidu_netdisk_backup/plugin_info.json
> +        "zh_cn": "readme.md"
找不到文件

2024-05-30 13:16 UTC, AnzhiZhang requested changes

2024-05-30 13:16 UTC, AnzhiZhang commented on plugins/baidu_netdisk_backup/plugin_info.json
> +        "zh_cn": "readme.md"
找不到文件

2024-05-30 13:36 UTC, moran0710 commented on plugins/baidu_netdisk_backup/plugin_info.json
> +        "zh_cn": "readme.md"
已经修复（readme要和开发文件夹在同一目录下，才发现

2024-05-30 14:49 UTC, AnzhiZhang commented on plugins/baidu_netdisk_backup/plugin_info.json
> +        "zh_cn": "readme.md"
相对路径就行，理论上可以写 ..

2024-05-30 14:49 UTC, merged

2024-07-31 19:19 UTC, Fallen-Breath commented
仓库链接 https://github.com/moran0710/MinecraftServer_BaiduNetdisk_backup 已失效，请及时更新。目前已通过提交 64ffb559327b6e4bec7966ab5127523034d9c6d6 暂时禁用了此插件