add show_message_time
MCDReforged/PluginCatalogue pull request #367
Opened 2024-07-25 21:51 UTC by jokerben-cn

---

## 检查以下事项 | Check the following:

- 仓库 URL、分支和 `related_path` 正确且 `mcdreforged.plugin.json` 位于应当存在的位置
  Repository URL, branch and `related_path` are correct and `mcdreforged.plugin.json` file exists at the correct path

- 根据 [文档](https://mcdreforged.readthedocs.io/zh_CN/latest/plugin_dev/plugin_catalogue.html#label)，检查插件标签正确且合适  
  Plugin labels are correct and appropriate according to [documentation](https://mcdreforged.readthedocs.io/en/latest/plugin_dev/plugin_catalogue.html#label)

- 确保 `mcdreforged.plugin.json` 和 `plugin_info.json` 中的插件 ID 与在本仓库创建的文件夹名称一致
  Plugin ID in `mcdreforged.plugin.json` and `plugin_info.json` match the name of the folder created in this repository

- 在介绍中简要阐明插件功能，在 README 中详细阐明插件用法，避免含糊不清。确保潜在用户有理由考虑使用您的插件
  Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the README. Avoid vague descriptions. Ensure that potential users have a reason to consider using your plugin

- [x] 我已检查并确认以上所有项目
  I have checked and confirmed all the above

2024-07-29 03:12 UTC, Ra1ny-Yuki commented
重复pr，请自行确认需要合并的内容并关闭多余的pr

2024-08-26 13:19 UTC, AnzhiZhang requested changes

2024-08-26 13:19 UTC, AnzhiZhang commented on plugins/show_message_time/plugin_info.json
> +    "labels": ["tool"],
应该是 `information`

2024-08-26 13:20 UTC, AnzhiZhang commented
This PR has been inactive for a long while, it will be closed at this moment. Please feel free to open a new one as needed.

2024-08-26 13:20 UTC, closed without merging