基于QQChat旧版的扩展插件,魔改并增加了大量功能
MCDReforged/PluginCatalogue pull request #369
Opened 2024-08-08 07:12 UTC by LoosePrince

功能比较定制化
魔改了大部分内容并增加了部分功能,于2022年11月9日至目前已维护将近两年
详情请查[文档](https://github.com/LoosePrince/PF-GUGUBot/blob/main/README.md)

---

## 检查以下事项 | Check the following:

- 仓库 URL、分支和 `related_path` 正确且 `mcdreforged.plugin.json` 位于应当存在的位置
  Repository URL, branch and `related_path` are correct and `mcdreforged.plugin.json` file exists at the correct path

- 根据 [文档](https://mcdreforged.readthedocs.io/zh_CN/latest/plugin_dev/plugin_catalogue.html#label)，检查插件标签正确且合适  
  Plugin labels are correct and appropriate according to [documentation](https://mcdreforged.readthedocs.io/en/latest/plugin_dev/plugin_catalogue.html#label)

- 确保 `mcdreforged.plugin.json` 和 `plugin_info.json` 中的插件 ID 与在本仓库创建的文件夹名称一致
  Plugin ID in `mcdreforged.plugin.json` and `plugin_info.json` match the name of the folder created in this repository

- 在介绍中简要阐明插件功能，在 README 中详细阐明插件用法，避免含糊不清。确保潜在用户有理由考虑使用您的插件
  Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the README. Avoid vague descriptions. Ensure that potential users have a reason to consider using your plugin

- [x] 我已检查并确认以上所有项目
  I have checked and confirmed all the above

2024-08-08 07:31 UTC, alex3236 commented
你的repo没有使用[原插件的GPL3.0协议](https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/LICENSE)，另README中指向原插件的链接是失效状态

2024-08-08 07:39 UTC, LoosePrince commented
我已补上[GPL3.0协议](https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/LICENSE)协议，至于原插件在很久前就已经失联了，提供的原插件链接是失联前我们所能够保留的链接，这不是我们所能够控制的

2024-08-08 07:42 UTC, alex3236 commented
> 我已补上[GPL3.0协议](https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/LICENSE)协议，至于原插件在很久前就已经失联了，提供的原插件链接是失联前我们所能够保留的链接，这不是我们所能够控制的

如果我没有理解失误，https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/qq_chat 仍在维护且上周刚刚发布2.2.0

2024-08-08 07:48 UTC, LoosePrince commented
好的，我们会将其新的链接列入原插件列表，但同时我们将保留旧版的链接，虽然他已经失效

2024-08-08 08:32 UTC, AnzhiZhang commented
> 好的，我们会将其新的链接列入原插件列表，但同时我们将保留旧版的链接，虽然他已经失效

你提到的两个插件都在维护，CoolQAPI 已经更名并升级为 QQAPI https://mcdreforged.com/en/plugin/qq_api

2024-08-08 08:34 UTC, AnzhiZhang approved these changes
LGTM，解决CI错误即可

2024-08-08 08:38 UTC, LoosePrince commented
> > 好的，我们会将其新的链接列入原插件列表，但同时我们将保留旧版的链接，虽然他已经失效
> 
> 你提到的两个插件都在维护，CoolQAPI 已经更名并升级为更通用的 QQAPI，个人建议修改关于“ CoolQAPI 已失联”的描述 https://mcdreforged.com/en/plugin/qq_api

好的

2024-08-08 08:45 UTC, AnzhiZhang commented
以QQChat插件作者身份发言：
readme 中[使用条款](https://github.com/LoosePrince/PF-GUGUBot/blob/main/README.md#%E4%BD%BF%E7%94%A8%E6%9D%A1%E6%AC%BE)部分属于基于开源协议GPL的补充条款，如果作者完全拥有权利可以添加此类条款。但是，该插件部分代码权利属于QQChat开发者，根据QQChat的开源协议，无权添加此类条款。我会到该仓库提出移除，如果需要会提出GitHub DMCA takedown，我也注意到该仓库存在相同问题：https://github.com/LoosePrince/PF-CoolQAPI。基于此，我不同意在这些条款移除前合并到插件仓库

@Fallen-Breath 插件仓库处理新插件时是否有责任在合理范围内审查插件的版权情况，和作者提出的权利主张？

2024-08-08 08:48 UTC, LoosePrince commented
> 以QQChat插件作者身份发言： readme 中[使用条款](https://github.com/LoosePrince/PF-GUGUBot/blob/main/README.md#%E4%BD%BF%E7%94%A8%E6%9D%A1%E6%AC%BE)部分属于基于开源协议GPL的补充条款，如果作者完全拥有权利可以添加此类条款。但是，该插件部分代码权利属于QQChat开发者，根据QQChat的开源协议，无权添加此类条款。我会到该仓库提出移除，如果需要会提出GitHub DMCA takedown，我也注意到该仓库存在相同问题：[https://github.com/LoosePrince/PF-CoolQAPI。基于此，我不同意在这些条款移除前合并到插件仓库](https://github.com/LoosePrince/PF-CoolQAPI%E3%80%82%E5%9F%BA%E4%BA%8E%E6%AD%A4%EF%BC%8C%E6%88%91%E4%B8%8D%E5%90%8C%E6%84%8F%E5%9C%A8%E8%BF%99%E4%BA%9B%E6%9D%A1%E6%AC%BE%E7%A7%BB%E9%99%A4%E5%89%8D%E5%90%88%E5%B9%B6%E5%88%B0%E6%8F%92%E4%BB%B6%E4%BB%93%E5%BA%93)
> 
> @Fallen-Breath 插件仓库处理新插件时是否有责任在合理范围内审查插件的版权情况，和作者提出的权利主张？

好的，我们将会移除 使用条款 项

2024-08-08 09:50 UTC, AnzhiZhang commented
@LoosePrince 文档的链接仍然不正确

2024-08-08 10:02 UTC, LoosePrince commented
> @LoosePrince 文档的链接仍然不正确

好的，我们将进行修改
移除旧版且已失效的`QQChat旧版`和`CoolQAPI`的链接，并按照如下指向目前可以访问的链接
QQChat -> `https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/qq_chat`
QQAPI -> `https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/qq_api`

2024-08-08 10:09 UTC, AnzhiZhang commented
还是没有通过检查，请注意 `introduction` 是受到 `related_path` 影响的，您可以修改自己的仓库或 PR 提供的文件

2024-08-08 10:23 UTC, AnzhiZhang commented
除了 introduction 不在 https://github.com/LoosePrince/PF-GUGUBot/tree/main/GUGUbot 路径下，没有看出来其他问题。似乎报错的提示与该问题无关，是否是仓库为 template 导致？报错的问题可以等 CI 作者来看一下

2024-08-08 10:31 UTC, LoosePrince commented
> 除了 introduction 不在 https://github.com/LoosePrince/PF-GUGUBot/tree/main/GUGUbot 路径下，没有看出来其他问题。似乎报错的提示与该问题无关，是否是仓库为 template 导致？报错的问题可以等 CI 作者来看一下

添加了一个白板文档（仅包含指向正确文档的链接），关闭了项目模板

2024-08-09 03:01 UTC, Fallen-Breath commented
> @Fallen-Breath 插件仓库处理新插件时是否有责任在合理范围内审查插件的版权情况，和作者提出的权利主张？

当然可以

2024-08-09 03:04 UTC, Fallen-Breath requested changes
请正确配置 introduction 文件的路径。`https://raw.githubusercontent.com/LoosePrince/PF-GUGUBot/master/GUGUbot/readme.md` 是 404 的

2024-08-09 04:25 UTC, LoosePrince commented
> 请正确配置 introduction 文件的路径。是 404 的`https://raw.githubusercontent.com/LoosePrince/PF-GUGUBot/master/GUGUbot/readme.md`

我修改了路径配置，现在 `https://raw.githubusercontent.com/LoosePrince/PF-GUGUBot/main/GUGUbot/README.md` 可以访问

2024-08-09 11:14 UTC, merged