Add plugin AnotherTranslateAPI as a dependency lib
MCDReforged/PluginCatalogue pull request #385
Opened 2024-08-28 06:58 UTC by Mooling0602

> 这是未发布插件\[MSync\]DeathTips（为扩展插件MatrixSync功能的一个子插件，将于后续发布）的必需依赖。

---

## 检查以下事项 | Check the following:

- 仓库 URL、分支和 `related_path` 正确且 `mcdreforged.plugin.json` 位于应当存在的位置
  Repository URL, branch and `related_path` are correct and `mcdreforged.plugin.json` file exists at the correct path

- 根据 [文档](https://mcdreforged.readthedocs.io/zh_CN/latest/plugin_dev/plugin_catalogue.html#label)，检查插件标签正确且合适  
  Plugin labels are correct and appropriate according to [documentation](https://mcdreforged.readthedocs.io/en/latest/plugin_dev/plugin_catalogue.html#label)

- 确保 `mcdreforged.plugin.json` 和 `plugin_info.json` 中的插件 ID 与在本仓库创建的文件夹名称一致
  Plugin ID in `mcdreforged.plugin.json` and `plugin_info.json` match the name of the folder created in this repository

- 在介绍中简要阐明插件功能，在 README 中详细阐明插件用法，避免含糊不清。确保潜在用户有理由考虑使用您的插件
  Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the README. Avoid vague descriptions. Ensure that potential users have a reason to consider using your plugin

- [x] 我已检查并确认以上所有项目
  I have checked and confirmed all the above

2024-08-28 07:17 UTC, alex3236 commented
请提供`en_us`的introduction

2024-08-28 07:35 UTC, Mooling0602 commented
> 请提供`en_us`的introduction

已完成

2024-08-28 18:34 UTC, AnzhiZhang commented
文档中提到

> 为MCDR插件[MSync]DeathTips的必需依赖。

根据文档介绍，我没有想到该插件的其它应用场景。

如果作为仅供文档中提到的插件使用，不应当发布为通用 API 插件。如果可以作为通用 API，烦请完善文档，说明应用场景和使用方法。

2024-08-28 18:35 UTC, AnzhiZhang requested changes
文档中提到

> 为MCDR插件[MSync]DeathTips的必需依赖。

根据文档介绍，我没有想到该插件的其它应用场景。

如果作为仅供文档中提到的插件使用，不应当发布为通用 API 插件。如果可以作为通用 API，烦请完善文档，说明应用场景和使用方法。

2024-08-29 02:24 UTC, Mooling0602 commented
> 文档中提到
> 
> > 为MCDR插件[MSync]DeathTips的必需依赖。
> 
> 根据文档介绍，我没有想到该插件的其它应用场景。
> 
> 如果作为仅供文档中提到的插件使用，不应当发布为通用 API 插件。如果可以作为通用 API，烦请完善文档，说明应用场景和使用方法。

更新了README，增加了“用途”、“文档”和“使用此API的项目”部分。

2024-08-29 02:32 UTC, AnzhiZhang approved these changes
LNBTM

2024-09-01 04:47 UTC, Mooling0602 commented
请求同时添加该插件：[MSync]DeathTips

2024-09-01 12:38 UTC, AnzhiZhang commented
一个 PR 做一件事。请为不同范畴的修改提交独立的 PR

https://github.com/MCDReforged/PluginCatalogue/pull/354#issuecomment-2212982488

2024-09-01 12:46 UTC, Mooling0602 commented
似乎没有办法在该pr未处理完成时发起另一个pr

Andy Zhang ***@***.***> 于 2024年9月1日周日 20:39写道：

> 一个 PR 做一件事。请为不同范畴的修改提交独立的 PR
>
> #354 (comment)
> <https://github.com/MCDReforged/PluginCatalogue/pull/354#issuecomment-2212982488>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MCDReforged/PluginCatalogue/pull/385#issuecomment-2323322897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDI4C3CQH5ILQ2QF2KQL6LLZUMDGRAVCNFSM6AAAAABNHTCLICVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRTGMZDEOBZG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-01 12:57 UTC, AnzhiZhang commented
> 似乎没有办法在该pr未处理完成时发起另一个pr

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

2024-09-01 13:23 UTC, Mooling0602 commented
Not planned.

2024-09-01 13:23 UTC, closed without merging