Add tnt_plugin
MCDReforged/PluginCatalogue pull request #418
Opened 2024-10-02 05:11 UTC by LBY123165

---

- [x] 我已阅读并检查，此 PR 符合 [贡献指南](https://github.com/MCDReforged/PluginCatalogue/blob/master/CONTRIBUTING_cn.md) 中的要求
  I have read and checked that my PR meets the requirements in the [Contributing Guidelines](https://github.com/MCDReforged/PluginCatalogue/blob/master/CONTRIBUTING.md)

2024-10-02 05:18 UTC, alex3236 requested changes
无论 README 还是 description 还是帮助命令都没说明白这玩意干啥用的……
另：插件 ID 和名称过于宽泛，建议至少与“轮盘赌”和“游戏”相关联，而不是 “tnt” 或 “tnt_plugin” 这种莫名其妙的名
另：轮盘赌 roulette

2024-10-02 05:18 UTC, LBY123165 commented
> 无论 README 还是 description 还是帮助命令都没说明白这玩意干啥用的……

正在重写readme.md

2024-10-03 10:56 UTC, LBY123165 commented
> 无论 README 还是 description 还是帮助命令都没说明白这玩意干啥用的…… 另：插件 ID 和名称过于宽泛，建议至少与“轮盘赌”和“游戏”相关联，而不是 “tnt” 或 “tnt_plugin” 这种莫名其妙的名 另：轮盘赌 roulette

已完成

2024-10-03 11:04 UTC, alex3236 commented on plugins/tnt_roulette/plugin_info.json
> +	"labels": [],
```suggestion
	"labels": ["tool"],
```

2024-10-03 11:04 UTC, alex3236 commented on plugins/tnt_roulette/plugin_info.json
> +	"branch": "main",
```suggestion
	"branch": "main",
	"related_path": "TNT",
```
不必在 repo 里放俩 `mcdreforged.plugin.json`，只留 `TNT/` 那个，然后在这加上 `related_path` 就行

2024-10-03 11:12 UTC, LBY123165 commented
> 没考虑到这个问题……先这么放一段时间吧（

我再塞一份readme进去？

2024-10-03 11:15 UTC, LBY123165 commented
> > > 没考虑到这个问题……先这么放一段时间吧（
> > 
> > 
> > 我再塞一份readme进去？
> 
> 你要是急的话 我建议你直接把TNT这个文件夹去掉 里面东西全部移出来，然后刚加上去那个related_path删了

不急，放着吧那就，就是给服里玩做完了寻思传一份出来（）

2024-10-03 11:17 UTC, alex3236 commented on plugins/tnt_roulette/plugin_info.json
> +        "zh_cn": "README.md"
```suggestion
        "en_us": "../README.md",
        "zh_cn": "../README.md"
```

2024-10-03 11:18 UTC, alex3236 approved these changes
LGTM

2024-10-03 11:43 UTC, merged