Add ColorlogFixHandler as a plugin-packaged custom handler
MCDReforged/PluginCatalogue pull request #420
Opened 2024-10-30 15:10 UTC by Mooling0602

此插件提供了对MCDR内置bukkit_handler的改进，使Leaves等服务端的部分特殊日志可以被正常解析。

---

- [x] 我已阅读并检查，此 PR 符合 [贡献指南](https://github.com/MCDReforged/PluginCatalogue/blob/master/CONTRIBUTING_cn.md) 中的要求
  I have read and checked that my PR meets the requirements in the [Contributing Guidelines](https://github.com/MCDReforged/PluginCatalogue/blob/master/CONTRIBUTING.md)

2024-10-30 15:21 UTC, Mooling0602 commented
> 又另，考虑向 MCDR 的 AbstractMinecraftHandler 提交 PR，因为其似乎已有去除颜色代码的功能，但没有囊括完全。你引用的库实际上基于 regex，可以直接挪过去

感谢你的建议，鉴于这是首次自定义类型的服务端处理器以插件形式提交到仓库供有需要的人使用，若通过，将对后续同类型插件的开发和发行产生积极影响，所以我将保持此提交入库请求。

2024-10-30 15:26 UTC, alex3236 commented
> 感谢你的建议，鉴于这是首次自定义类型的服务端处理器以插件形式提交到仓库供有需要的人使用，若通过，将对后续同类型插件的开发和发行产生积极影响，所以我将保持此提交入库请求。

我并没有觉得入库有问题，只是建议你考虑提交 PR，具体怎么做与我无关 :)

2024-10-30 22:15 UTC, AnzhiZhang requested changes
看介绍，是 bukkit 限定，这个名称不合适

关于标签：建议考虑新增 `handler` 标签 @Fallen-Breath

2024-10-31 01:59 UTC, alex3236 commented
另请参见
 https://github.com/MCDReforged/MCDReforged/issues/345

2024-10-31 06:12 UTC, Mooling0602 commented
> 看介绍，是 bukkit 限定，这个名称不合适
> 
> 关于标签：建议考虑新增 `handler` 标签 @Fallen-Breath

名称是根据实际情况考虑的，大多数用户会直观的发现无法解析的地方都发生在带了颜色的日志处，所以使用此名称较为直观，插件ID仍然保留较为准确的名称

2024-10-31 12:59 UTC, AnzhiZhang commented
> 名称是根据实际情况考虑的，大多数用户会直观的发现无法解析的地方都发生在带了颜色的日志处，所以使用此名称较为直观，插件ID仍然保留较为准确的名称

所以是不是仅限 bukkit 吧

2024-10-31 13:15 UTC, Mooling0602 commented
插件的加载后显示名称已经修改完成，为避免潜在问题，没有全局改动

2024-11-01 09:41 UTC, closed without merging

2024-11-01 09:41 UTC, Mooling0602 commented
Closed as not planed.