add WebsocketAPI
MCDReforged/PluginCatalogue pull request #92
Opened 2021-02-18 15:15 UTC by BelowZeroKelvin

2021-02-18 15:25 UTC, zhang-anzhi commented
description `Enable other plugins to use WebSocket` 不太合适吧

2021-02-19 01:37 UTC, zhang-anzhi requested changes

2021-02-19 01:37 UTC, zhang-anzhi commented on readme.md
> +| [WebsocketAPI](https://github.com/BelowZeroKelvin/MCDR-WebsocketAPI) | [BelowZeroKelvin](https://github.com/BelowZeroKelvin) | Enable other plugins to use WebSocket |
`Enable other plugins to use WebSocket` 不太合适吧

2021-02-19 02:16 UTC, BelowZeroKelvin commented on readme.md
> +| [WebsocketAPI](https://github.com/BelowZeroKelvin/MCDR-WebsocketAPI) | [BelowZeroKelvin](https://github.com/BelowZeroKelvin) | Enable other plugins to use WebSocket |
翻译了一下确实不太对，现在修改了一下

2021-02-19 03:06 UTC, merged